import os
from datetime import datetime
import matplotlib.pyplot as plt
import pandas as pd

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    Image
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
from reportlab.lib.enums import TA_CENTER


# =====================================================
# SAFE RISK CLASSIFICATION
# =====================================================
def classify_risk(score):
    try:
        score = float(score)
    except:
        score = 0

    if score >= 75:
        return "Low Risk"
    elif score >= 50:
        return "Medium Risk"
    else:
        return "High Risk"


# =====================================================
# MAIN REPORT GENERATOR
# =====================================================
def generate_financial_report(
        username,
        profile,
        expenses,
        salary,
        advice,
        score,
        history):

    os.makedirs("reports", exist_ok=True)
    os.makedirs("reports/charts", exist_ok=True)

    file_path = f"reports/{username}_financial_intelligence_report.pdf"

    doc = SimpleDocTemplate(file_path, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    # =====================================================
    # 1️⃣ COVER PAGE
    # =====================================================
    title_style = ParagraphStyle(
        name="TitleStyle",
        parent=styles["Heading1"],
        alignment=TA_CENTER,
        textColor=colors.HexColor("#E53935")
    )

    elements.append(Spacer(1, 2 * inch))
    elements.append(Paragraph(
        f"{datetime.now().strftime('%B %Y')} Financial Intelligence Report",
        title_style))
    elements.append(Spacer(1, 0.3 * inch))

    elements.append(Paragraph(
        f"Prepared For: {username}",
        styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph(
        "Generated by Agentic Financial AI Assistant",
        styles["Normal"]))

    elements.append(PageBreak())

    # =====================================================
    # 2️⃣ EXECUTIVE SNAPSHOT
    # =====================================================
    total_expense = sum(
        float(v) for v in expenses.values()
        if str(v).replace(".", "", 1).isdigit()
    )

    savings = float(salary) - total_expense if salary else 0
    savings_rate = round((savings / salary) * 100, 2) if salary else 0

    elements.append(Paragraph("Executive Financial Snapshot",
                              styles["Heading1"]))
    elements.append(Spacer(1, 0.3 * inch))

    snapshot_data = [
        ["Total Income", f"₹ {salary:,}"],
        ["Total Expenses", f"₹ {int(total_expense):,}"],
        ["Net Savings", f"₹ {int(savings):,}"],
        ["Savings Rate", f"{savings_rate}%"],
        ["Financial Health Score", f"{score}/100"]
    ]

    snapshot_table = Table(snapshot_data, colWidths=[3*inch, 2.5*inch])
    snapshot_table.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('BACKGROUND', (0,0), (-1,0), colors.whitesmoke)
    ]))

    elements.append(snapshot_table)
    elements.append(PageBreak())

    # =====================================================
    # 3️⃣ EXPENSE ANALYSIS TABLE
    # =====================================================
    elements.append(Paragraph("Expense Analysis",
                              styles["Heading1"]))
    elements.append(Spacer(1, 0.3 * inch))

    expense_table_data = [["Category", "Amount (₹)"]]

    safe_expenses = {}
    for k, v in expenses.items():
        try:
            val = float(v)
            if val > 0:
                safe_expenses[k] = val
                expense_table_data.append([k, f"{int(val):,}"])
        except:
            continue

    expense_table = Table(expense_table_data,
                          colWidths=[3*inch, 2.5*inch])
    expense_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey)
    ]))

    elements.append(expense_table)
    elements.append(Spacer(1, 0.4 * inch))

    # =====================================================
    # SAFE PIE CHART
    # =====================================================
    categories = list(safe_expenses.keys())
    values = list(safe_expenses.values())

    if values and sum(values) > 0:

        plt.figure()
        plt.pie(values, labels=categories, autopct='%1.1f%%')
        plt.title("Expense Distribution")

        pie_path = f"reports/charts/{username}_pie.png"
        plt.savefig(pie_path)
        plt.close()

        elements.append(Image(pie_path, width=4*inch, height=4*inch))

    else:
        elements.append(Paragraph(
            "No valid expense data available for visualization.",
            styles["Normal"]))

    elements.append(PageBreak())

    # =====================================================
    # 4️⃣ RISK SECTION
    # =====================================================
    elements.append(Paragraph("Risk Assessment",
                              styles["Heading1"]))
    elements.append(Spacer(1, 0.3 * inch))

    risk = classify_risk(score)

    elements.append(Paragraph(
        f"Financial Health Score: {score}/100",
        styles["Normal"]))
    elements.append(Paragraph(
        f"Risk Classification: {risk}",
        styles["Normal"]))

    elements.append(PageBreak())

    # =====================================================
    # 5️⃣ RECOMMENDATIONS
    # =====================================================
    elements.append(Paragraph("Smart AI Recommendations",
                              styles["Heading1"]))
    elements.append(Spacer(1, 0.3 * inch))

    if advice:
        for tip in advice:
            elements.append(Paragraph(f"• {tip}",
                                      styles["Normal"]))
            elements.append(Spacer(1, 0.1 * inch))
    else:
        elements.append(Paragraph(
            "No major financial risks detected.",
            styles["Normal"]))

    elements.append(PageBreak())

    # =====================================================
    # 6️⃣ FORECAST
    # =====================================================
    elements.append(Paragraph("6-Month Savings Forecast",
                              styles["Heading1"]))
    elements.append(Spacer(1, 0.3 * inch))

    projected_savings = savings * 6

    elements.append(Paragraph(
        f"Projected savings in next 6 months: ₹ {int(projected_savings):,}",
        styles["Normal"]))

    doc.build(elements)

    return file_path
